//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP_CAMERA_PHUONGNGHI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int contact_id { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public Nullable<int> ct_from_id { get; set; }
    
        public virtual ContactForm ContactForm { get; set; }
    }
}
