//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP_CAMERA_PHUONGNGHI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class footer
    {
        public int footer_id { get; set; }
        public string Title { get; set; }
        public string Email { get; set; }
        public string Hotline { get; set; }
        public string worktime { get; set; }
        public Nullable<System.TimeSpan> start_time { get; set; }
        public Nullable<System.TimeSpan> end_time { get; set; }
        public string chutaikhoan { get; set; }
        public string sotaikhoan { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
