//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP_CAMERA_PHUONGNGHI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GALLERY
    {
        public int id_gallery { get; set; }
        public int id_product { get; set; }
        public string thumbnail { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
