//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP_CAMERA_PHUONGNGHI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int detail_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> price_product { get; set; }
        public Nullable<int> num { get; set; }
        public Nullable<int> total_price_product { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> card_id { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Oder Oder { get; set; }
    }
}
