//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP_CAMERA_PHUONGNGHI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLIDE
    {
        public int id_slide { get; set; }
        public string image { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    }
}
