//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP_CAMERA_PHUONGNGHI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slide
    {
        public int slide_id { get; set; }
        public string TitleSlide { get; set; }
        public string DescriptionSlide { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public Nullable<int> Sort { get; set; }
        public string Link { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
