//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP_CAMERA_PHUONGNGHI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.InteropServices;


    public partial class tbProduct
    {
        
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbProduct()
        {
            this.Carts = new HashSet<Cart>();
            this.KhoHangs = new HashSet<KhoHang>();
        }
        
        public int product_id { get; set; }
        [Display(Name = "Tên s?n ph?m")]
        public string Name { get; set; }
        public string SeoTitle { get; set; }
        public Nullable<bool> Status { get; set; }
        [Display(Name = "Hình ?nh")]
        public string Thumnail { get; set; }
        [Display(Name = "Giá")]
        public Nullable<int> Price { get; set; }
        [Display(Name = "Giá khuy?n mãi")]
        public Nullable<int> PromotionPrice { get; set; }
        public string TonKho { get; set; }
        public Nullable<int> BaoHanh { get; set; }
        [Display(Name = "Miêu t?")]
        public string Desciption { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> brand_id { get; set; }
        public string MetaKey { get; set; }
        public string MetaDescription { get; set; }
        [Display(Name = "Ngày t?o s?n ph?m")]
        public Nullable<System.DateTime> CreateDate { get; set; }
        [Display(Name = "Ngày c?p nh?t s?n ph?m")]
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> rank { get; set; }
        public Nullable<int> comment_id { get; set; }
    
        public virtual Brand Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual Category Category { get; set; }
        public virtual CommentProduct CommentProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhoHang> KhoHangs { get; set; }
    }
}
